### ISSUE TITLE
Scenario for the upgrade agent need to be fixed

### ISSUE THREAD

**Issue by IgorGuz2000** [elastic/e2e-testing#1643]
https://github.com/elastic/e2e-testing/pull/1642
This scenario:

```gherkin
@upgrade-agent
@nightly
@skip:windows
Scenario Outline: Upgrading the installed <os> agent
  Given a "<os>" agent "stale" is deployed to Fleet with "tar" installer
    And agent is in version "stale"
    And certs are installed
    And the "elastic-agent" process is "restarted" on the host
  When agent is upgraded to version "latest"
  Then agent is in version "latest"
```
this need to be fixed because is it not working as designed first stem never installed stale version.

**Comment by IgorGuz2000** [comment]
Use the branch that I created to run the scenario, and you will see that stale version never installed

**Comment by mdelapenya** [comment]
Revisiting this issue.

After talking to @jlind23 we agreed in defining an upgrade matrix of **released** artifacts as stale agents, so that the code will install a released version of the elastic-agent, trying to upgrade it to the current branch's version.

From:
```gherkin
Scenario Outline: Upgrading the installed agent
  Given an agent "stale" is deployed to Fleet with "tar" installer
    And certs are installed
    And the "elastic-agent" process is "restarted" on the host
  When agent is upgraded to version "latest"
  Then agent is in version "latest"
```

We should move to (for 8.2 branch), in example:
```gherkin
Scenario Outline: Upgrading the installed agent
  Given an agent in "<stale-version>" is deployed to Fleet with "tar" installer
    And certs are installed
    And the "elastic-agent" process is "restarted" on the host
  When agent is upgraded to version "latest"
  Then agent is in version "latest"
Examples:
| stale-version  |
| 7.17.1         |
| 8.1.1          |
| 8.1.2          |
```

@jlind23 could you please fill in this upgrade matrix?

| branch | upgrade versions |
|--------|-------------------|
| main (8.3) | |
| 8.2 | |
| 8.1 | |
| 7.17 | |

I have another question: why we need to `restart` the agent process before the upgrade happens, to see the certificates? Is this something we can do before the installation so that we can skip the restart?

**Comment by jlind23** [comment]
@mdelapenya The matrix should look like as follow
| branch | upgrade versions |
|--------|-------------------|
| main (8.3) | main (Self upgrade) |
| 8.2 | 8.2, main|
| 8.1 | 8.1, 8.2, main|
| 7.17 | 7.17, 8.1, 8.2, main|

> I have another question: why we need to restart the agent process before the upgrade happens, to see the certificates? Is this something we can do before the installation so that we can skip the restart?

I do not want to give a wrong answer. @elastic/elastic-agent-control-plane can you answer here?

**Comment by blakerouse** [comment]
The matrix provided by @jlind23 is correct.

The one that is the most important is main -> main.

**Comment by mdelapenya** [comment]
> The matrix provided by @jlind23 is correct.
> 
> The one that is the most important is main -> main.

When upgrading from main branch (current HEAD) to main, Fleet returns: 

```json
{
  "statusCode":400,
  "error":"Bad Request",
  "message":"agent d7071c36-34dc-47b7-8c65-4fba51958dbb is not upgradeable"
}
```
