### ISSUE TITLE
[DISCUSS] Add the ability to test cgroup v2 behaviour

### ISSUE THREAD

**Issue by jlind23** [elastic/e2e-testing#1976]
After discussing with @fearful-symmetry, it seems pretty mandatory to automate all tests related to cgroup v2 behaviour and metrics. So far everything was done manually or through some scripting but having some automation in place would be a safeguard against regression.

Is there any way to automate those tests using the e2e-testing framework? Like preloading some cgroup configuration and test that the metrics reported are the same whatever the beats/agent version we are using? Values, types, etc..

cc @fearful-symmetry

**Comment by fearful-symmetry** [comment]
So, to add some context here, cgroups is particularly thorny because OS distros, and cgroups consumers such as docker, can utilize cgroups in a variety of ways. The OS itself can either be "pure" cgV1, "pure" cgv2, or "hybird". Within that, hybrid mode is basically a free-for-all, and differing docker versions can operate within either V1 or V2, depending on the version. V1 and V2 are sufficiently different that a lot of code logic is required to deal these edge cases. A test matrix would need to look something like this, if we want to properly cover cgroups support:


- Pick OSes that represent the three basic cgroups config (something like centos, an Ubuntu LTS, and the latest Fedora)
- Within those OSes, test the system module (specifically system/process) and the docker module running natively on the OSes
- Repeat the above test, but running within docker within those OSes
- We may want to add cloud container services such as GKE as well.

**Comment by jlind23** [comment]
@elastic/observablt-robots any toughts?

**Comment by v1v** [comment]
Hey Julien,

We are this week a bit under-staffed with the festivity season, if you don't mind, let's wait for the upcoming week to answer those questions 🙏 

Thanks

**Comment by jlind23** [comment]
Sure. 👍🏼

**Comment by cachedout** [comment]
@jlind23 Is there a particular reason that you're favoring E2E testing over the existing integration test suites inside of Beats which, as I understand it, already make heavy use of Dockerized environments?

**Comment by cmacknz** [comment]
We could freeze it, I don't know if we have anyone free to help work on actually writing E2E tests for this.

I would be curious why we can't add some initial automated testing using docker within the beats integration tests. I understand that won't cover everything, but some test coverage is better than none if that is where we are now.

From the E2E framework perspective, we would just need the ability to run on VMs with CentOS and Ubuntu LTS images + Kubernetes? Is that already possible?

I don't think Fedora is in our support matrix so we likely don't need to deal with that one.

**Comment by fearful-symmetry** [comment]
Right now, if we wanted "better than nothing" tests for this, we could just run a certain subset of interested tests (process data mostly, maybe some other things) natively on the ubuntu VM, then again on docker. We might want some more specialized tests or environment setups to test particular edge cases, but there (in theory) shouldn't be much standing in the way of just improving what we have now. Ubuntu is a good place to start, since it uses cgroups in hybird mode, which is where most of the funky edge cases are.

**Comment by cachedout** [comment]
> From the E2E framework perspective, we would just need the ability to run on VMs with CentOS and Ubuntu LTS images + Kubernetes? @cachedout That is likely already possible?

@cmacknz Not presently, but soon-ish. The ability for the E2E to run using VMs is [in progress](https://github.com/elastic/e2e-testing/issues/1682). Support for k8s is [there already](https://github.com/elastic/e2e-testing/tree/main/e2e/_suites/kubernetes-autodiscover).

> Right now, if we wanted "better than nothing" tests for this, we could just run a certain subset of interested tests (process data mostly, maybe some other things) natively on the ubuntu VM, then again on docker. 

IMHO this is the best approach given where we are today. It sounds to me like there's a fair amount that can be covered with this approach. Then, once native-VM support is available in E2E we could revist this?

**Comment by kuisathaverat** [comment]
@cachedout I am not sure if we should move this issue to other repo

**Comment by kuisathaverat** [comment]
obsolete
