### ISSUE TITLE
[Ingest manager] Test persistent, containerised agent 

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#214]
We want to check that the backend processes are restarted after the container is restarted

```gherkin
Scenario: Restarting an agent
  Given an agent is deployed to Fleet with persistent install
  When the host is restarted
  Then the "elastic-agent" process is in the "started" state on the host
    And the "filebeat" process is in the "started" state on the host
    And the "metricbeat" process is in the "started" state on the host
```

A persistent install means there is a service in the linux system, restarting the process after reboots

**Comment by EricDavisX** [comment]
Hi!
To test the Agent with persistence, we would modify the testing as such:
1) download the .deb file, instead of .tar.gz

2) Then install it as:
sudo dpkg -i elastic-agent-7.9.0-amd64.deb
(if you wish to not call sudo directly that's ok, so long as the user is Administrator privilege)

3) then the deploy steps become this:
elastic-agent enroll https://a721ba95c0ef46a0889adf4e935d7ddc.us-east-1.aws.staging.foundit.no:443 aHVvZXYzTUJaOG9VNXlvMHNydDc6cmFSeG9NRmxRWXVFaE5jWlVhekhndw==
systemctl enable elastic-agent
systemctl start elastic-agent

note the lack of the 'dot' . in the enroll command, it is intentionally seeking to test the binary registered with the .deb install (not the local one).

A good note for us to review and double check... when installed like this, the local files will be in a different location. Do we have any references to local files like logs or paths?  if we have log refs then we'll need to parameterize them.  I was hoping we'd have a log-parsing step to review for errors, but I don't think we ever worked on that yet.

**Comment by EricDavisX** [comment]
THEN - if we want to be twice as fun, we can modify the scenario to test the .rpm install too.  :)

That scenario's changes could be:
download the .rpm file, instead of .deb

Then install it as:
sudo rpm –i elastic-agent-7.9.0-x86_64.rpm
(if you wish to not call sudo directly that's ok, so long as the user is Administrator privilege)

then the deploy steps become this, as an Administrator user (sudo):
elastic-agent enroll https://a721ba95c0ef46a0889adf4e935d7ddc.us-east-1.aws.staging.foundit.no:443 aHVvZXYzTUJaOG9VNXlvMHNydDc6cmFSeG9NRmxRWXVFaE5jWlVhekhndw==
systemctl enable elastic-agent
systemctl start elastic-agent

**Comment by mdelapenya** [comment]
Do we run `systemctl` after the enrollment?
>    elastic-agent enroll https://a721ba95c0ef46a0889adf4e935d7ddc.us-east-1.aws.staging.foundit.no:443 aHVvZXYzTUJaOG9VNXlvMHNydDc6cmFSeG9NRmxRWXVFaE5jWlVhekhndw==
>    systemctl enable elastic-agent
>    systemctl start elastic-agent

> A good note for us to review and double check... when installed like this, the local files will be in a different location. Do we have any references to local files like logs or paths? if we have log refs then we'll need to parameterize them. I was hoping we'd have a log-parsing step to review for errors, but I don't think we ever worked on that yet.
No, we don't check logs or anything apart from the processes themselves. I agree, it would be fine to at least check for their existence
