### ISSUE TITLE
elastic-agent diagnostics command tests

### ISSUE THREAD

**Issue by michel-laterman** [elastic/e2e-testing#2204]
We need to add some e2e tests for the `elastic-agent diagnostics` commands. Including the functionality of `elastic-agent diagnostics collect` when `pprof` and the `buffer` configs have been enabled.

As the archives produced by `collect` may change structure I'm not sure how much validation of the contents.

**Comment by mdelapenya** [comment]
Hey @michel-laterman I have a question: do we need the entire setup to test a command? Is this anything that could be tested at the unit test level? I ask because if we are going the check the structure of a file/bundle, I'm not sure if we need the entire stack: es, kibana, fleet-server and the agent.

I'd prefer stepping back and double check if the functionality can be unit tested: simulating events, mocking a service, etc.

Of course, I could be wrong and we need all the system running, but I'd like to do an extra effort in think about this, and IIRC we started a similar discussion in https://github.com/elastic/e2e-testing/issues/1060#issuecomment-824757611

**Comment by mdelapenya** [comment]
I guess that you'll need to build a scenario based on the Given-When-Then pattern:

```gherkin
Given an agent is deployed to Fleet with "tar" installer
  And ???
When the "diagnostics collect" elastic-agent command is executed
Then ???
```

**Comment by michel-laterman** [comment]
Covered by elastic-agent integration tests
