### ISSUE TITLE
Package not added to e2e policies due to Api change

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/e2e-testing#2967]
Hi All,

We are recently observing the flakiness in e2e tests due to package not being added under policy during running of tests. 

Current error logs:
```
response="{\"statusCode\":400,\"error\":\"Bad Request\",\"message\":\"Package policy is invalid: inputs.logfile.streams.system.auth.vars.preserve_original_event: Preserve original event is required\\ninputs.logfile.streams.system.auth.vars.tags: Tags is required\"}" retry=23 statusCode=400
```

On confirmation with Fleet team, we came to know about api changes that require now Preserve original event  and Tags parameter to successfully add the integration.

So, till fixes are made in current code, we can skip out the related e2e tests that uses policies.

**Comment by v1v** [comment]
@cmacknz @kpollich , I don't know if you are aware of this particular API change, but the e2e-testing are broken. Who is working, from your teams, on adapting the required changes in this project?

**Comment by kpollich** [comment]
This is because of an update in the `system` package that includes these required variables. We haven't made an API change here to cause this breakage.  @nchaulet and I spoke with @pazone on Slack a bit yesterday and determined the best path forward is probably to skip these tests. 

We're shipping package policy API changes in 8.5 here: https://github.com/elastic/kibana/issues/132263, so until these land it's probably best to skip these as we'll need to rethink them following the API changes anyway.

**Comment by dikshachauhan-qasource** [comment]
This issue is fixed now under https://github.com/elastic/e2e-testing/pull/2999

Hence, we are closing this out.

Thanks.
