### ISSUE TITLE
[Elastic Agent] Agent Upgrade feature test

### ISSUE THREAD

**Issue by michalpristas** [elastic/e2e-testing#341]
Scenario should be as follow:
#### 2 versions of agent are available (must differ in last commit)
  - first agent is the one which is installed
  - second one is made available using some public API or local fileserver (must be available at `{uri}:{port}/beats/elastic-agent/{tar_name}`

#### Second agent artifacts is made available 
for local test i'm using fileserver with artifacts at `~/server/beats/elastic-agent/*`
then from `~/server` i run `python3 -m http.server`

#### Update is initiated either using UI (manual tests) or using API (manual/automated tests)
API for initiating upgrade using fileserver serving at localhost
```
curl -X POST -H 'kbn-xsrf: true'  -u elastic:changeme http://localhost:5601/api/ingest_manager/fleet/agents/{AGENT_ID}/upgrade \
  -H 'Content-Type: application/json' \
 -d '{"source_uri":"http://localhost:8000","version":"8.0.0"}'
```

If fleet does not send SourceURI it is good to configure `agent.download.sourceURI` to `http://localhost:8000` in `elastic-agent.yml`

#### Agent is listed as `UPDATING` in fleet 
- with file server this will be only for a fraction of second or couple of seconds max (update is very fast)

#### Agent version is changed and agent is listed as `ONLINE` in fleet 
- state should be running
- all beats has to be started and collecting again based on config assigned

No ERROR should be reported during this procedure.

### Prerequisites 
https://github.com/elastic/kibana/pull/78810
https://github.com/elastic/beats/pull/21461

**Comment by EricDavisX** [comment]
Thanks Michal!  Do you want me to take a first stab at the feature file?  Manu and I are happy to review.  to start... I'll list out what I see, and post it to the desc above which we can modify. I have a plan I think may be fairly feasible to implement.  The syntax below is contingent on the test being able to introspect what the current snapshot version is and what the prior version is.  I think we can do that.  And the vague 'current' and 'prior' citation allows us to write actual tests in a given GA line that upgrade the current shipped version to the current-in-test version (I think).  Anyhow, below is a first pass draft to consider.  I did (painfully) add back in the steps for the filebeat, metric, and endpoint about 'sending new data' to ES.  we took those steps out, and I submit we shouldn't wait to put them back in, we just needed better depth of understanding to do it and Michal, I think you can help us out here!

file:
agent_upgrades.feature

@agent_endpoint_upgrade
Feature: Agent Endpoint Upgrade tests
  Scenarios for Agent to deploy with and without Endpoint and upgrade it and validate data sent out.

@deploy-agent-and-upgrade
Scenario: Deploying an Agent and then upgrading it to the latest
  Given the prior version agent is deployed to "centos" with Fleet
    And the agent is listed in Fleet as "online"
  When the agent upgraded is initiated to "current" version
  Then agent is listed as UPDATING in fleet
	And update action is ACKed in Fleet
	And agent version is changed in Fleet
	And agent is listed as ONLINE in Fleet
    And the "elastic-agent" process is in the "started" state on the host
    And the "filebeat" process is in the "started" state on the host
    And the "metricbeat" process is in the "started" state on the host
	And "filebeat" sends new data to ES
	And "metric" sends new data to ES

@deploy-endpoint-with-agent-and-upgrade
Scenario: Deploying Endpoint with Agent and upgrade it
  Given the prior snapshot agent is deployed to "centos" with Fleet
    And the agent is listed in Fleet as "online"
    And the "Elastic Endpoint Security" integration is "added" in the policy
    And the "Elastic Endpoint Security" datasource is shown in the policy as added
    And the host name is shown in the Administration view in the Security App as "online"
    And Then the policy response will be shown in the Security App
    And the agent is listed in Fleet as "online"
  When the agent upgraded is initiated to "current" version
  Then agent is listed as UPDATING in fleet
	And update action is ACKed in Fleet
	And agent version is changed in Fleet
	And agent is listed as ONLINE in Fleet
    And the "elastic-agent" process is in the "started" state on the host
    And the "elastic-endpoint" process is in the "started" state on the host
	And "endpoint" sends new data to ES

**Comment by ph** [comment]
@EricDavisX Just to make sure I understand who will do what on this issue. You wrote the feature file, @michalpristas will write the hooks in the cuccumber framework with the help of @mdelapenya? 

cc @KseniaElastic

**Comment by EricDavisX** [comment]
that's a good plan as I see it.

**Comment by EricDavisX** [comment]
Further on this, @michalpristas and @mdelapenya and @neptunian ...me and Michal had a quick chat.  The above is doable with current architecture, but it doesn't actually cover the code that is executed in the Agent fully.  So we're considering how to account further.

I think if we had a -force flag in the API that would remove the Kibana restriction on upgrading version x.y.z to version x.y.z that could suffice.  In that case, we could test the current PR agent in the current version of Kibana master could ‘force’ an upgrade to basically the same version, but it will be trying out the code in the Agent PR, that we want.  I think that makes sense, thoughts?  I don’t think we can test this without more code change to remove the (intentional) restriction.

To re-use the phrasing Michal had started with me earlier, we'll have:
- latest stable GA upgrade to newer snapshot build Agent (nightly e2e test, as cited in comments above)
- current master PR build can upgrade to master SNAPSHOT build (/package call dev testing)
... this 2nd test is dependent on removing the restriction as noted.  And it will basically run in nightly e2e as well, effectively just as a test of upgrading to itself, which still tests out the code paths even if the versions don’t change.  But in this case, we’ll need find a way to set which versions to inspect for.  Or maybe we can mark that 2nd test as special and somehow skip it during nightly CI.
@mdelapenya Do you have ideas on how we could do that or how else we'd choose to handle it?

**Comment by neptunian** [comment]
@EricDavisX If I understand correctly you need to be able to test to upgrading to the same version in order to test new builds.  Does this have to be accessible through the UI (via a button) or would making a call to the API suffice?

**Comment by EricDavisX** [comment]
@neptunian we could survive with just API usage, as the test here will consume it as such.

**Comment by neptunian** [comment]
@EricDavisX Could this be something we do for 7.11 or is there a reason we'd need it in 7.10?

**Comment by EricDavisX** [comment]
The additional API support is preferred for 7.11, not needed or wanted for 7.10.   @neptunian we're in good shape for 7.10. :)

**Comment by EricDavisX** [comment]
we are fully unblocked to implement this now.  all feature tests are done and 7.10 is working well.

**Comment by EricDavisX** [comment]
this is done and can be closed, it was only ever targeted towards 'Agent' upgrade not Fleet, just fyi (hence why I updated the description)
