### ISSUE TITLE
Investigate why Ceph tests are flaky, as it seems to fail with quite a frequency

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#607]
It seems it's always the same Ceph version

>Step there are no errors in the index: Errors where found for ceph-7.10-SNAPSHOT on Metricbeat's metricbeat-7.10-ceph-master-97985eb-nautilus-centos-7-x86_64-z3sknpmt index: 9 error/s out of 9

> Step there are no errors in the index: Errors where found for ceph-8.0.0-SNAPSHOT on Metricbeat's metricbeat-8.0.0-ceph-master-97985eb-nautilus-centos-7-x86_64-offqwosn index: 10 error/s out of 10

cc/ @jsoriano

**Comment by jsoriano** [comment]
@mdelapenya in the beats repo we set a custom 120 seconds timeout in Ceph integration tests (over the default 60s). If I remember well, the problem was that Ceph metrics endpoint didn't return valid metrics till the service has been up for 60 seconds. Is it possible that we are timeouting here before or around these 60 seconds?

**Comment by mdelapenya** [comment]
Let me investigate that, because it could be related: we see this issue intermittently, so it could be very related.

I'll debug it and send a proposal PR, thanks!

**Comment by mdelapenya** [comment]
Reopening after skipping the tests
